services:
  md-chat:
    image: ghcr.io/mikndotdev/chat:latest
    container_name: md-chat
    ports:
      - "3000:80"
    environment:
      LOGTO_APP_ID: "YOUR_LOGTO_APP_ID"
      LOGTO_APP_SECRET: "YOUR_LOGTO_APP_SECRET"
      LOGTO_ENDPOINT: "https://(your-logto-instance).logto.io"
      LOGTO_COOKIE_SECRET: "a-very-long-and-random-secret-string-for-cookies"
      DATABASE_URL: "postgres://chatuser:chatpassword@db:5432/chatdb"
      REDIS_URL: "redis://:redispassword@redis:6379/0"
      S3_ENDPOINT: ""
      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      S3_BUCKET_NAME: ""
      S3_REGION: ""
      S3_UPLOAD_DIR: ""
      S3_PUBLIC_URL: ""
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: chat_db
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: chat_redis
    environment:
      REDIS_PASSWORD: redispassword
    command: redis-server --requirepass redispassword
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
